---
name: CarbonXchange CI/CD

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

env:
  TERRAFORM_VERSION: "1.6.6"
  KUBECTL_VERSION: "1.28.0"
  HELM_VERSION: "3.13.0"

jobs:
  infrastructure-lint:
    name: Infrastructure Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format Check
        run: |
          cd infrastructure/terraform
          terraform fmt -check -recursive

      - name: Terraform Validate
        run: |
          cd infrastructure/terraform
          terraform init -backend=false
          terraform validate

      - name: Install yamllint
        run: pip install yamllint

      - name: YAML Lint
        run: |
          cd infrastructure
          yamllint -c .yamllint kubernetes/ ansible/ ci-cd/

      - name: Install ansible-lint
        run: pip install ansible-lint

      - name: Ansible Lint
        run: |
          cd infrastructure/ansible
          ansible-lint playbooks/ roles/

  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f code/backend/requirements.txt ]; then 
              pip install -r code/backend/requirements.txt
          fi

      - name: Run tests
        run: |
          cd code/backend
          python -m pytest --cov=. --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        if: always()
        with:
          file: ./code/backend/coverage.xml
          flags: backend

  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: code/frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd code/frontend
          npm ci

      - name: Run linter
        run: |
          cd code/frontend
          npm run lint

      - name: Run tests
        run: |
          cd code/frontend
          npm test -- --coverage

      - name: Build
        run: |
          cd code/frontend
          npm run build

  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

      - name: Run Checkov for Terraform/K8s
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infrastructure/
          framework: terraform,kubernetes
          output_format: sarif
          output_file_path: checkov-results.sarif

  build-and-deploy:
    name: Build and Deploy
    needs: [infrastructure-lint, backend-test, frontend-test, security-scan]
    if: |
      github.event_name == 'push' && 
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build frontend
        run: |
          cd code/frontend
          npm ci
          npm run build

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f code/backend/requirements.txt ]; then
              pip install -r code/backend/requirements.txt
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Add your deployment steps here
      # Examples:
      # - Build and push Docker images
      # - Deploy to ECS/EKS
      # - Run database migrations
      # - Update infrastructure with Terraform
      # - Deploy to Kubernetes cluster

      - name: Deploy notification
        run: |
          echo "Deployment completed successfully"
          # Add notification logic (Slack, email, etc.)
