apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.appName }}-redis-pvc"
  namespace: '{{ .Values.namespace | default "carbonxchange" }}'
  labels:
    app: "{{ .Values.appName }}-redis"
    component: redis
    environment: "{{ .Values.environment }}"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "{{ .Values.redis.storageClass }}"
  resources:
    requests:
      storage: "{{ .Values.redis.storage }}"
