apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.appName }}-secrets"
  namespace: '{{ .Values.namespace | default "carbonxchange" }}'
  labels:
    app: "{{ .Values.appName }}"
    component: secrets
    environment: "{{ .Values.environment }}"
  annotations:
    compliance.carbonxchange.io/data-classification: "secret"
type: Opaque
data:
  database-url: "{{ .Values.database.url | b64enc }}"
  jwt-secret: "{{ .Values.backend.jwtSecret | b64enc }}"
  encryption-key: "{{ .Values.backend.encryptionKey | b64enc }}"
  api-key-salt: "{{ .Values.backend.apiKeySalt | b64enc }}"
  mysql-root-password: "{{ .Values.database.rootPassword | b64enc }}"
  mysql-password: "{{ .Values.database.password | b64enc }}"
  redis-url: "{{ .Values.redis.url | b64enc }}"
  redis-password: "{{ .Values.redis.password | b64enc }}"
  api-key: "{{ .Values.backend.apiKey | b64enc }}"
