apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-frontend"
  namespace: '{{ .Values.namespace | default "carbonxchange" }}'
  labels:
    app: "{{ .Values.appName }}-frontend"
    component: frontend
    environment: "{{ .Values.environment }}"
spec:
  type: "{{ .Values.frontend.service.type }}"
  ports:
    - port: { { .Values.frontend.servicePort } }
      targetPort: { { .Values.frontend.containerPort } }
      protocol: TCP
      name: http
  selector:
    app: "{{ .Values.appName }}-frontend"
    component: frontend
